version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    container_name: 'tch-postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 6432:5432

  blockscout:
    depends_on:
      - db
    image: domecloud/tch-exp:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "TCH"
    restart: always
    container_name: 'tch-blockscout'
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'base'
        ETHEREUM_JSONRPC_HTTP_URL: https://rpc.mrfoxchain.com
        DATABASE_URL: postgresql://postgres:@host.docker.internal:6432/blockscout?ssl=false
        ECTO_USE_SSL: false
    ports:
      - 4001:4000

